version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: gradle test
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/libs
          destination: prefix
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle jar
          command: gradle jar
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/libs
          destination: prefix
