version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: gradle test
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - .
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle jar
          command: gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - attach_workspace:
          at: /tmp/workspace

workflows:
  version: 2
  flow:
    jobs:
      - test
      - package:
          requires:
            - test
